### PR TITLE
eslint, prettier conflict.

### PR DESCRIPTION
**Pull request by arvandf**
@rrebase I'm kinda stuck with prettier, eslint conflicts. Problem is that when we save the file eslint reformats the code and some of these rules conflict with prettier.  As you can see in the picture, when I save the file the spaces are removed automatically and it generates error! I tried different solutions, none worked. Do you have a solution?
image
image

Also after the last merge, I have to set End of line option to LF instead of CRLF
image

### CODE REVIEW

**Comment by rrebase** [comment]
@arvandf What VSCode extensions do you have installed?

I am using the extensions defined in `frontend/.vscode/extensions.json`, which are
- Prettier - Code formatter (`esbenp.prettier-vscode`) 5.1.3
- ESLint (`dbaeumer.vscode-eslint`) 2.1.8

With these I don't have any issues with the code snippet you provided.

**Comment by arvandf** [comment]
@rrebase I'm using the same extensions with specified with version. Not sure why this isn't happening in your environment since prettier puts the spaces at the beginning of the line and eslint removes those when the file is saved. 
This error was mention [here](https://github.com/prettier/eslint-plugin-prettier/issues/116) as well but the solution doesn't apply.

**Comment by rrebase** [comment]
@arvandf and you also opened your VSCode project from in `/frontend` so that `.vscode/settings.json` applies?

**Comment by arvandf** [comment]
@rrebase yes (I posted the question on StackOverflow, hopefully, somebody will answer)

**Comment by rrebase** [comment]
@arvandf any luck? I actually remember someone having this issue due to duplicate vscode linter extensions. A workout (obviously not a solution) would be to disable your any eslint extensions you have an only use prettier and `yarn lint --fix` any eslint issues before commiting.

Here's an interesting SO post about the different plugins we're using https://stackoverflow.com/questions/44690308/whats-the-difference-between-prettier-eslint-eslint-plugin-prettier-and-eslint

**Comment by arvandf** [comment]
@rrebase It seems Prettier and ESlint are not fully compatible with each other. I ended up using the guidelines from [How to use Prettier with ESLint and TypeScript in VSCode](https://khalilstemmler.com/blogs/tooling/prettier/).  It ended up with changing eslintrc, adding prettierrc. And thanks for the link I had prettier-eslint extension installed and that was causing issue too.  I just have to see why the tests are failing now!

**Comment by arvandf** [comment]
@rrebase it seems to be finally working and I can get back to creating the PR for filtering assignees 😄

**Comment by rrebase** [comment]
Yes, by default prettier and eslint are not compatible, but that's what those plugins are supposed to solve. I think they work fine and the culprit was your conflicting `prettier-eslint` extension all along 🤔  Is the issue resolved in current master without the extension?

The guidelines you pointed to also seem to use the same plugins. The `@typescript-eslint`& `react/recommended`  plugins are actually quite useful and wouldn't want to drop them if it wasn't needed.

**Comment by arvandf** [comment]
@rrebase I tried again on master and it seems to be working without `prettier-eslint` extension, although I get other errors which need can be resolved by setting the end of line from `CLRF `to `LR`. I think VS code needed a restart after uninstalling 😞! 
I reverted back the old settings for `.eslintrc` and vs code settings. But I think the PR can be useful because prettier formatting is run on the whole project. What do you think?

**Comment by rrebase** [comment]
I assume you're working on Windows, where `CLRF` is the default. Yeah, try to save files with Unix end of line `LF` in this project for consistency.

Not sure about this PR. The code is already prettified by the last PR & the huge diff is due to the `"singleQuote": true` change, which I don't have a strong opinion about. I guess it's better not to clutter git history since double quotes are fine as well as the default.

I'm sorry you've had such a painful onboarding to this project 😕  Hopefully once you dig into actual issues, we can discuss more meaningful challenges 💪

**Comment by arvandf** [comment]
@rrebase yes, it was quite painful to set up things 😭. Looking forward to those good challenges 😄 
A few things:

- I'm using windows and it's not possible to set LF for all files. One solution I found was to add following rule to` .eslintrc`:
```
    "prettier/prettier": [
      "error",
      {
        "endOfLine": "auto"
      }
    ]
```
I can add this to the next PR.

- I know that single quote vs double quote is opinionated, but please read [this ](https://stackoverflow.com/questions/2373074/single-vs-double-quotes-vs#:~:text=The%20Short%20Answer,convention%20and%20use%20it%20regularly.)before closing the PR. (I'm trying my best to save the PR 😄 )

**Comment by rrebase** [comment]
I used to be a big fan on single quotes. It was even a pet peeve of mine seeing double quotes in javascript & python for the same reasons as the SO post you linked to.

But then came `black` for formatting python with double as the default (same as prettier) and I gave up. Both have strong 
arguments for double quotes. Note: The python code in this project is using double quotes.

In the end it really doesn't matter & I'm actually really greatful for the auto formatters existing & being quite opinionated. It's much easier to dive into a project with the same formatting as I can mentally get a quicker grasp of the important bits.

**Comment by arvandf** [comment]
@rrebase the problem is `lf `on windows is that I can't build the project. I will have [this ](https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-delete-cr-prettier-prettier)problem for the whole project.

**Comment by rrebase** [comment]
Okay, the `auto` should be fine as a workaround. If something else comes up related to this, let's force `lf` via git.

**Pull request closed without merging**
