### PR TITLE
Upgrade prettier and fix prettier and lint issues

### PR DESCRIPTION
**Pull request by arvandf**
I was trying to use optional chaining for a PR, then realized that the prettier version is old. In this pull request I have:

-  Upgraded prettier in package.json

- Change  the following line in the package.json (otherwise yarn fix lint wouldn't work):

` "lint": "eslint \"**/*.{js,ts,tsx}\""`

-  Ran `yarn lint --fix`

It seems that yarn lint --fix wasn't correctly running before so a lot correction has been made to the files.

### CODE REVIEW

**Comment by rrebase** [comment]
Thank you for the contribution! Noticed that you commited `package-lock.json`, but we're using yarn and thus have `yarn.lock`, otherwise the PR looks good. 🙂

**Comment by rrebase** [comment]
It seems that CI is failing because of multiple Cypress versions defined in `yarn.lock`

I've actually seen this before. Setting a specific version of Cypress should help using `resolution` in `package.json`, see https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by arvandf** [comment]
@rrebase I could get this far from last night.
Just to recap, I wanted to create a PR for filtering the assignees, but it seemed the project would build because it wouldn't support optional chaining. From yesterday I am trying to upgrade the dependencies but I have faced some issues:

1.  It seems that yarn upgrade doesn't change the package.json file.
To resolve this  I found some help at the following links:
https://github.com/yarnpkg/yarn/issues/2042
https://github.com/yarnpkg/yarn/issues/2042#issuecomment-449798652

and ended up running these commands

```
yarn global add syncyarnlock // install syncyarnlock globally
yarn upgrade --latest // update dependencies, updates yarn.lock
syncyarnlock -s -k // updates package.json with versions installed from yarn.lock
yarn install // updates yarn.lock with current version constraint from package.json
```

After that I ran` yarn lint --fix`  and tried to remove some of the issues.

2. After upgrading the depencies I was getting an error, because react-app script wouldn't support the latest version of eslint. So I had to remove eslint
https://github.com/wesbos/eslint-config-wesbos/issues/17
`yarn remove eslint`

3. The build had some errors because there were some renamings (mostly formContext to FormProvider) in react-hooks
https://github.com/react-hook-form/react-hook-form/pull/1471

4. In CreateTaskDialog, line 255 was commented (Couldn't fix it)

**Comment by arvandf** [comment]
> It seems that CI is failing because of multiple Cypress versions.
> 
> Setting a specific version of Cypress with `resolutions` key in `package.json` might help https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
> 
> This seems relevant: [cypress-io/cypress#4595](https://github.com/cypress-io/cypress/issues/4595)

The latest CI details indicate that Cypress is dependent on package-lock.json,  @rrebase could you help to resolve these issues and upgrade the packages please?

```
  echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
  echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
```

**Comment by rrebase** [comment]
@arvandf I'll take a look and try to fix these issues.

**Comment by rrebase** [comment]
@arvandf Upgrading npm packages can be quite a chore due to dependency hell.

I initially continued from your latest commit and fixed the issues you mention above,
but then something made one of the [CI steps hang](https://app.circleci.com/pipelines/github/rrebase/knboard/288/workflows/e81934dc-a696-41dd-8548-0366d813ca5d/jobs/1017). Not sure what's causing it since there are so many package upgrades.

My thoughts:
- Instead of `yarn upgrade` It's usually better to go through the packages one-by-one. I like to use the VSCode extension `Version Lens`, which shows the latest versions in `package.json` and allows you to easily bump the version & check the changelogs.
- It seems that a lot is currently dependant on react-scripts dependency versions and the 4.0 is coming soon, so I'd wait for that and currently stick to just prettier upgrade - got a passing build based on your first commit [here](https://github.com/rrebase/knboard/pull/27)

**Comment by arvandf** [comment]
@rrebase Thanks for fixing it so quickly 😄. It also makes total sense to close this PR.

- I didn't know about Version Lens, it seems very useful. 👏 

- `.vscode/settings.json` got added automatically because I opened both projects in one VS code. I'll open the projects separately from now on.

**Pull request closed without merging**
