### PR TITLE
Add keyboard commands

### LINKED ISSUE #15: More shortcuts
Ideally I would like to see shortcuts for all the possible actions, initially with hints. 
A good example is the "Create issue" button (hint is currently only shown for MacOS though).

### PR DESCRIPTION
**Pull request by doylemark**
resolves #15 

Following binds were added

- [x] Add card to column
- [x] Lock Task
- [x] Delete Task
- [x] Create Board

### CODE REVIEW

**Comment by doylemark** [comment]
will fix

**Comment by doylemark** [comment]
Tests need to be rerun, will pass then. Codeclimate review appears to be redundant.

**Comment by doylemark** [comment]
Not sure the "duplicated code" is really duplicated code, but rather similar markup 😆 Otherwise ready to merge pending feedback/review :)

**Comment by rrebase** [comment]
Hey, it looks good 🙂. I think the column creation shortcut should be changed to something else though. Currently it collides with the default Chrome "Go to tab" shortcut at least on macOS, which also uses (⌘+number).

I'll change the similary check configuration of codeclimate, it's a bit absurd at the moment.

**Comment by doylemark** [comment]
True.. I noticed that myself, perhaps CMD+OPT+N would work?=

**Comment by rrebase** [comment]
> True.. I noticed that myself, perhaps CMD+OPT+N would work?

Yeah, that would work.

**Comment by doylemark** [comment]
Settled on META+SHIFT+N.

**Pull request merged**
